name 'actifio-chef'
maintainer 'Nigel Wright'
maintainer_email 'nigel.wright@dimensiondata.com'
license 'Apache-2.0'
description 'Allows for host registration and mounting of data from Actifio'
long_description 'Allows for host registration and mounting of data from Actifio'
version '3.0.34'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/nwright-nz/chef-actifio/issues'
source_url 'https://github.com/nwright-nz/chef-actifio'
